config/routes.rb
Rails.application.routes.draw do
  post 'orders/new' => 'orders#new'
  resources :orders
  get 'search' => 'search#index'

  resources :food_items
  get 'home/index'

  get 'contact_us' => 'home#contact_us'

  get 'menu' => 'home#menu'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  has_many :order_food_items
  has_many :orders, :through => :order_food_items
  def self.search(search)
    where("name  || description ILIKE ?", "%#{search}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
end

app/models/order_food_item.rb
class OrderFoodItem < ApplicationRecord
  belongs_to :order
  belongs_to :food_item
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @food_items = FoodItem.all.order("created_at desc").last(5)
  end

  def contact_us
  end

  def menu
    @sections = Section.order(:id)
    if params[:section].blank?
      @food_items = FoodItem.all
    else
      @food_items = FoodItem.where(section: params[:section])
    end

    if params[:sort_column]
      @food_items = @food_items.order("#{params[:sort_column]} #{params[:sort_direction]}")
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    if params[:id].present?
        @order = Order.find_by_id(params[:id])
    else
      
    end
  end

  # Post /orders/new
  def new
    if params[:food_item].present?
      @order = Order.new
      @food_item = FoodItem.find_by_id(params[:food_item])
      @order.food_item = @food_item
    end

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @food_item = FoodItem.find_by_id(params[:food_item])
    @order.food_item = @food_item
    @order.save
    redirect_to order_path(:id => @order.id), notice: 'Thank you for your order page'
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_name, :customer_address, :customer_phone, :food_item_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:search]
      @food_items = FoodItem.search(params[:search]).order("created_at DESC")
    else
      @food_items = FoodItem.all.order("created_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_util.rb
class CurrencyUtil
  def self.to_currency(number)
    ActionController::Base.helpers.number_to_currency(number, precision: 0, unit: "VND ", separator: ",", delimiter: ",", format: "%n %u")
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :food_item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.collection_select :section_id, Section.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :food_item_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-bordered table-stripe">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section.name %></td>
        <td><%= image_tag(food_item.image_url, :size => "260x180")  %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<%= link_to 'Back', url_for(:back), class: 'form-control' %>
<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= @food_item.name %></h4>
    <p class="card-text"><%= @food_item.description %></p>
    <p class="card-text"><%= @food_item.price %> VND</p>
    <p class="card-text"><%= image_tag(@food_item.image_url, :size => "460x360")  %></p>
    <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
    <%= hidden_field_tag :food_item, @food_item.id%>
    <%= submit_tag "Order Now", class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>

app/views/home/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  %>
  </head>

  <body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Blog</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" data-method="delete" href="<%= destroy_user_session_path %>">Log Out</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_article_path %>">New Article</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_path %>">Log In</a>
            </li>
          <% end %>
        </ul>

        <form class="form-inline my-2 my-lg-0">
          <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
          <%= submit_tag "Search" %>
          <% end %>
        </form>
      </div>
    </nav>
    <% unless flash.empty? %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= value %>
        <% end %>
      <% end %>
    </div>
    <!-- Yield to Controller -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/home/contact_us.html.erb
<h1>Contact US</h1>
<div class="row">
  <div class="col-sm-6">
    <address>
      <strong>DK Restaurant</strong>
      72 Le Thanh Ton St<br>
      District 1, HCM<br>
      Vietnam<br>
      Mobile: (+84) 933 835 848<br>
    </address>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.4398472296116!2d106.69961371499579!3d10.777585092320784!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f47d9c0e9b5%3A0x7bfa14b8cae00060!2zNzIgTMOqIFRow6FuaCBUw7RuLCBC4bq_biBOZ2jDqSwgUXXhuq1uIDEsIEjhu5MgQ2jDrSBNaW5oLCBWaWV0bmFt!5e0!3m2!1sen!2s!4v1497586222338" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/home/index.html.erb
<% @food_items.each.with_index do |item, index| %>
  <% if index.even? %>
    <div class="row">
       <div class="col-lg-6">
         <div class="card">
           <div class="card-block">
             <h4 class="card-title"><%= link_to item.name, food_item_path(id: item.id) %></h4>
             <p class="card-text"><%= CurrencyUtil.to_currency(item.price) %></p>
             <p class="card-text"><%= image_tag(item.image_url, :size => "260x180")  %></p>
             <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
             <%= hidden_field_tag :food_item, item.id%>
             <%= submit_tag "Order Now", class: "btn btn-secondary" %>
             <% end %>
           </div>
         </div>
       </div>
  <% else %>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-block">
            <h4 class="card-title"><%= link_to item.name, food_item_path(id: item.id) %></h4>
            <p class="card-text"><%= CurrencyUtil.to_currency(item.price) %></p>
            <p class="card-text"><%= image_tag(item.image_url, :size => "260x180")  %></p>
            <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
            <%= hidden_field_tag :food_item, item.id%>
            <%= submit_tag "Order Now", class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/home/menu.html.erb
<style>
  #limheight {
    -webkit-column-count: 2;
       -moz-column-count: 2;
            column-count: 2; /*3 in those rules is just placeholder -- can be anything*/
  }
  #limheight li {
    display: inline-block; /*necessary*/
  }
</style>

<ul class="nav nav-pills">
  <% @sections.each do |section| %>
    <li class="nav-item">
      <%= link_to "#{section.name}", menu_path(section: section.id), class: "nav-link #{params[:section]} #{section.id} #{params[:section].to_s==section.id.to_s && 'active'}" %>
    </li>
  <% end %>
</ul>

<div class='card card-block'>
  <%= form_tag nil, method: 'get' do %>
    <%= hidden_field_tag :section, params[:section]%>
    <div class='form-inline'>
      <%= select_tag :sort_column,  options_for_select([['Name', 'name'], ['Price', 'price']], params[:sort_column]), class: 'form-control'%>
      <%= select_tag :sort_direction, options_for_select([['Ascending', 'asc'], ['Desending', 'desc']], params[:sort_direction]), class: 'form-control' %>
      <%= submit_tag 'Apply', class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>
<% @food_items.each.with_index do |item, index| %>
  <% if index.even? %>
    <div class="row">
       <div class="col-lg-6">
         <div class="card">
           <div class="card-block">
             <h4 class="card-title"><%= link_to item.name, food_item_path(id: item.id) %></h4>
             <p class="card-text"><%= CurrencyUtil.to_currency(item.price) %></p>
             <p class="card-text"><%= image_tag(item.image_url, :size => "260x180")  %></p>
             <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
             <%= hidden_field_tag :food_item, item.id%>
             <%= submit_tag "Order Now", class: "btn btn-secondary" %>
             <% end %>
           </div>
         </div>
       </div>
  <% else %>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-block">
            <h4 class="card-title"><%= link_to item.name, food_item_path(id: item.id) %></h4>
            <p class="card-text"><%= CurrencyUtil.to_currency(item.price) %></p>
            <p class="card-text"><%= image_tag(item.image_url, :size => "260x180")  %></p>
            <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
            <%= hidden_field_tag :food_item, item.id%>
            <%= submit_tag "Order Now", class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #e3f2fd;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', home_index_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Menu', menu_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact US', contact_us_path, class: 'nav-link'%>
      </li>
    </ul>

      <%= form_tag(search_path, :method => "get", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search foods & drinks", class: "form-control mr-sm-2" %>
      <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DK Restaurant - Best place for your healthy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class='container'>
      <%= render 'layouts/navbar'%>
      <%= yield %>
      <div><br></div>
      <footer class='footer' style="background-color: #e3f2fd;">
        <div class='container' style="text-align: center;">
          <span style="font-size:9px">&copy;2017 DK Restaurant</span>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= link_to 'Back', url_for(:back) %>
<h2 align='center'>Create Order</h2>

<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
          <h3 class="card-title">You have made order for</h3>
          <p class="card-text"><%= @food_item.name %></p>
          <p class="card-text"><%= CurrencyUtil.to_currency(@food_item.price) %> VND</p>
          <p class="card-text"><%= image_tag(@food_item.image_url, :size => "130x90")  %></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
          <h3 class="card-title">Customer Info & Order Detail</h3>
          <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <%= form.text_field :customer_name, id: :order_customer_name, class: "form-control", placeholder: "Enter your name" %>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Address</label>
            <%= form.text_area :customer_address, id: :order_customer_address, class: "form-control", rows: "3" %>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail1">Phone</label>
            <%= form.text_area :customer_phone, id: :order_customer_phone, class: "form-control", placeholder: "+84 9000111" %>
          </div>
          <%= hidden_field_tag :food_item, @food_item.id%>
          <%= form.submit class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Customer address</th>
      <th>Customer phone</th>
      <th>Food item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer_name %></td>
        <td><%= order.customer_address %></td>
        <td><%= order.customer_phone %></td>
        <td><%= order.food_item %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<%= link_to 'Back to Menu Page', menu_path, class: 'form-control' %>
<div class="card">
  <span style="font-size:20px"><%= notice %></span>
  <div class="card-block">
    <p>
      <strong>Name:</strong>
      <%= @order.customer_name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @order.customer_address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @order.customer_phone %>
    </p>
  </div>

  <div class="card-block">
    <p>
      <strong>Item Name:</strong>
      <%= @order.food_item.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= CurrencyUtil.to_currency(@order.food_item.price) %>
    </p>

    <p>
      <strong>Quantity:</strong> 1
    </p>

    <p>
      <strong>Delivery Cost: </strong><%= CurrencyUtil.to_currency(20000)%>
    </p>
    <p>
      <strong>Total Cost:</strong>
      <%= CurrencyUtil.to_currency(@order.food_item.price + 20000) %>
    </p>

    <p>
      <strong>Order Created At:</strong>
      <%= @order.created_at.strftime("%A %H:%M [%b %d, %Y]") %>
    </p>
  </div>
</div>

app/views/search/index.html.erb
<style>
  #limheight {
    -webkit-column-count: 2;
       -moz-column-count: 2;
            column-count: 2; /*3 in those rules is just placeholder -- can be anything*/
  }
  #limheight li {
    display: inline-block; /*necessary*/
  }
</style>

<% @food_items.each.with_index do |item, index| %>
  <% if index.even? %>
    <div class="row">
       <div class="col-lg-6">
         <div class="card">
           <div class="card-block">
             <h4 class="card-title"><%= link_to item.name, food_item_path(id: item.id) %></h4>
             <p class="card-text"><%= CurrencyUtil.to_currency(item.price) %></p>
             <p class="card-text"><%= image_tag(item.image_url, :size => "260x180")  %></p>
             <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
             <%= hidden_field_tag :food_item, item.id%>
             <%= submit_tag "Order Now", class: "btn btn-secondary" %>
             <% end %>
           </div>
         </div>
       </div>
  <% else %>
      <div class="col-lg-6">
        <div class="card">
          <div class="card-block">
            <h4 class="card-title"><%= link_to item.name, food_item_path(id: item.id) %></h4>
            <p class="card-text"><%= CurrencyUtil.to_currency(item.price) %></p>
            <p class="card-text"><%= image_tag(item.image_url, :size => "260x180")  %></p>
            <%= form_tag(orders_new_path, :method => "post", id: "search-form", :class => 'form-inline my-2 my-lg-0' ) do %>
            <%= hidden_field_tag :food_item, item.id%>
            <%= submit_tag "Order Now", class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>